version: "3.9"

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: "10.1.0.100/24"

services:
  redis:
    networks:
      network:
        ipv4_address: 10.1.0.102
    image: redis/redis-stack
    container_name: redis
    volumes:
      - /data/redis:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  medicine_bot:
    networks:
      network:
        ipv4_address: 10.1.0.11
    build: .
    volumes:
      - ./database.db:/bot/database.db
    env_file:
      - .env
    container_name: medicine_bot

  celery_beat:
    networks:
      network:
        ipv4_address: 10.1.0.12
    image: medicinebot-medicine_bot
    env_file:
      - .env
    container_name: celery_beat
    depends_on:
      - medicine_bot
    entrypoint: [ "celery", "-A", "async_tasks.celery_init", "beat", "--loglevel=INFO" ]


  celery_worker:
    networks:
      network:
        ipv4_address: 10.1.0.13
    image: medicinebot-medicine_bot
    env_file:
      - .env
    container_name: celery_worker
    depends_on:
      - medicine_bot
    entrypoint: [ "celery", "-A", "async_tasks.celery_init", "worker", "--loglevel=INFO" ]
